yarnPath: .yarn/releases/yarn-4.9.1.cjs

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/types@*":
    dependencies:
      "@parcel/core": 2.9.3
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": 2.9.3
