yarnPath: .yarn/releases/yarn-4.9.4.cjs

nodeLinker: node-modules
#pnpMode: loose

packageExtensions:
  # Это правило говорит Yarn: "Основной CLI пакет 'nx'
  # неявно ожидает, что плагины @nx/workspace и @nx/nest будут доступны.
  # Пожалуйста, считай их его равноправными зависимостями (peer dependencies),
  # чтобы 'nx' мог их найти и загрузить при чтении nx.json".
  "nx@*":
    peerDependencies:
      "@nx/workspace": "*"
      "@nx/nest": "*"
