import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: '../focalm-server/schema.autogenerated.graphql',
  documents: 'graphql/**/*.graphql',
  generates: {
    'src/graphql.generated/_types.ts': {
      plugins: ['typescript'],
      config: {
        maybeValue: 'T | null | undefined',
      },
    },
    'src/graphql.generated/': {
      preset: 'near-operation-file',
      presetConfig: {
        extension: '.ts',
        baseTypesPath: '../../graphql/_types',
      },
      plugins: [
        'typescript-operations',
        {
          'typescript-urql': {
            withHooks: true,
            withComponent: false,
            withHOC: false,
            gqlImport: 'urql#gql', // или '@urql/core'
          },
        }
      ],
    },
  },
  ignoreNoDocuments: true,
};

export default config;
