import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { Request, Response } from 'express';

import { CurrentUser } from '../decorators/current-user';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './auth/auth.module';
import { FilesModule } from './files/files.module';
import { MenusModule } from './menus/menus.module';
import { UsersModule } from './users/users.module';

@Module({
  imports: [
    AuthModule,
    UsersModule,
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,

      autoSchemaFile: 'schema.autogenerated.graphql', // или join(process.cwd(), 'src/schema.gql')
      sortSchema: true,
      playground: true, // GraphQL Playground в dev
      introspection: true, // отключи в проде
      context: ({ req, res }: { req: Request & { user?: CurrentUser }; res: Response }) => ({ req, res }), // важно для auth
    }),
    MenusModule,
    FilesModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
