// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.19.1
// source: src/grpc/messages.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "messages";

/** Указываем, что используем 3-ю версию синтаксиса */

/** Основная сущность сообщения */
export interface Message {
  id: string;
  text: string;
  chatId: string;
  authorId: string;
  createdAt: Timestamp | undefined;
}

/** Запрос на создание сообщения */
export interface CreateMessageRequest {
  text: string;
  chatId: string;
  authorId: string;
}

/** Ответ после создания (возвращаем созданный объект) */
export interface CreateMessageResponse {
  message: Message | undefined;
}

/** Запрос на получение сообщений */
export interface GetMessagesByChatIdRequest {
  chatId: string;
  /** Опциональные параметры для пагинации */
  limit?: number | undefined;
  offset?: number | undefined;
}

/** Ответ со списком сообщений */
export interface GetMessagesByChatIdResponse {
  messages: Message[];
}

export const MESSAGES_PACKAGE_NAME = "messages";

/** Сервис, который будет реализовывать наш messages-service */

export interface MessagesServiceClient {
  /**
   * Метод для создания сообщения (используется GraphQL-мутацией)
   * Внутри он будет публиковать событие в Kafka
   */

  createMessage(request: CreateMessageRequest): Observable<CreateMessageResponse>;

  /** Метод для получения сообщений чата (используется GraphQL-квери) */

  getMessagesByChatId(request: GetMessagesByChatIdRequest): Observable<GetMessagesByChatIdResponse>;
}

/** Сервис, который будет реализовывать наш messages-service */

export interface MessagesServiceController {
  /**
   * Метод для создания сообщения (используется GraphQL-мутацией)
   * Внутри он будет публиковать событие в Kafka
   */

  createMessage(
    request: CreateMessageRequest,
  ): Promise<CreateMessageResponse> | Observable<CreateMessageResponse> | CreateMessageResponse;

  /** Метод для получения сообщений чата (используется GraphQL-квери) */

  getMessagesByChatId(
    request: GetMessagesByChatIdRequest,
  ): Promise<GetMessagesByChatIdResponse> | Observable<GetMessagesByChatIdResponse> | GetMessagesByChatIdResponse;
}

export function MessagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createMessage", "getMessagesByChatId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGES_SERVICE_NAME = "MessagesService";
