import Long from 'long';

/**
 * A local type definition representing the structure of a google.protobuf.Timestamp
 * as generated by ts-proto with the `forceLong=bigint` option.
 */
type Timestamp = {
  seconds: Long;
  nanos: number;
};

/**
 * Converts a JavaScript Date object to a gRPC Timestamp-like object.
 * @param d The Date object to convert.
 * @returns A Timestamp object, or `undefined` if the input is null/undefined.
 */
export const protobufTimestampFromDate = (d: Date): Timestamp => {
  const millis = d.getTime();
  return {
    seconds: Long.fromNumber(Math.floor(millis / 1000)),
    nanos: (millis % 1000) * 1_000_000,
  };
};

// The safe upper/lower limit for seconds that can be represented by a JS Date.
// JS Date is based on milliseconds stored as a `Number`, which is safe up to
// +/- 100,000,000 days from epoch, or ~273,790 years.
const MAX_SAFE_SECONDS = 8_640_000_000_000n; // Corresponds to 100,000,000 days in seconds

const MAX_SAFE_LONG_SECONDS = Long.fromBigInt(MAX_SAFE_SECONDS);
const MIN_SAFE_LONG_SECONDS = Long.fromBigInt(-MAX_SAFE_SECONDS);

/**
 * Converts a gRPC Timestamp-like object back to a JavaScript Date.
 * Includes a safety check to prevent creating a corrupted Date from an out-of-range timestamp.
 * @param stamp The Timestamp object to convert.
 * @returns A Date object, or `undefined` if the input is null/undefined.
 * @throws RangeError if the timestamp is outside the safe range for a native JS Date.
 */
export const protobufTimestampToDate = (stamp: Timestamp): Date => {
  // Before converting, check if the seconds are within the safe range for a JS Date.
  if (stamp.seconds.greaterThan(MAX_SAFE_LONG_SECONDS) || stamp.seconds.lessThan(MIN_SAFE_LONG_SECONDS)) {
    throw new RangeError(
      `Timestamp is outside the safe range for a JavaScript Date. Seconds: ${stamp.seconds.toString()}`
    );
  }

  // Convert the bigint `seconds` to a `Number` *before* multiplying to avoid overflow.
  // This is safe because we've already performed the range check above.
  return new Date(stamp.seconds.toNumber() * 1000 + Math.round(stamp.nanos / 1_000_000));
};
