import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';
import { Logger, Module } from '@nestjs/common';
import { GraphQLISODateTime, GraphQLModule } from '@nestjs/graphql';
import { JwtModule } from '@nestjs/jwt';
import { ScheduleModule } from '@nestjs/schedule';
import { GraphQLError, GraphQLFormattedError } from 'graphql';

import { ContextType } from '../context';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AuthModule } from './auth/auth.module';
import { AuthService } from './auth/auth.service';
import { UsersService } from './users/users.service';

@Module({
  imports: [
    ScheduleModule.forRoot(),
    AuthModule,
    JwtModule.register({ global: true }),
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,

      context: ({
        req,
        res,
        connectionParams,
      }: Pick<ContextType, `req` | `res`> & { connectionParams?: Record<string, string> }): ContextType => {
        // if (connectionParams) {
        //   const fakeReq = {
        //     ...req,
        //     headers: {
        //       authorization: connectionParams['Authorization'] ?? connectionParams['authorization'],
        //     },
        //   };
        //
        //   return { req: fakeReq as ContextType[`req`], res };
        // }
        return { req, res };
      },

      subscriptions: {
        'graphql-ws': true,
      },
      csrfPrevention: false,

      autoSchemaFile: 'schema.autogenerated.graphql', // или join(process.cwd(), 'src/schema.gql')
      sortSchema: true,
      playground: true, // GraphQL Playground в dev
      introspection: true, // отключи в проде

      formatError: (error): GraphQLFormattedError => {
        let stackTrace: string | undefined;

        if (error.extensions?.[`code`] === `UNAUTHENTICATED`) {
          Logger.error(`[GraphQL][ERROR] ${error.message}`, 'GQL-Exception');
        } else {
          // 1) Если это GraphQLError (который наследует Error), у него есть stack.
          if (error instanceof GraphQLError) {
            // Попробуем вытянуть кастомный stack из extensions.exception, если он есть
            const ext = error.extensions?.exception as { stack?: string; stacktrace?: string[] } | undefined;

            if (ext?.stack) {
              stackTrace = ext.stack;
            } else if (Array.isArray(ext?.stacktrace)) {
              stackTrace = ext.stacktrace.join('\n');
            }

            // fallback на стандартный GraphQLError.stack
            if (!stackTrace) {
              stackTrace = error.stack;
            }
          }
          // 2) Ещё на всякий случай: любое другое исключение, унаследованное от Error.
          else if (error instanceof Error) {
            stackTrace = error.stack;
          }

          // Логируем полный стектрейс на сервер
          Logger.error(
            `[GraphQL][ERROR] ${error.message} [code=${error.extensions?.[`code`] || '<none>'}]`,
            stackTrace,
            'GQL-Exception'
          );
        }

        // Клиенту отдадим только безопасное поле message + стандартные поля
        return {
          message: process.env.NODE_ENV === 'production' ? 'Internal server error' : error.message,
          locations: error.locations,
          path: error.path,
          extensions: {
            code: error.extensions?.code,
          },
        };
      },
    }),
  ],
  controllers: [AppController],
  providers: [
    AppService,
    {
      provide: 'DateTime',
      useValue: GraphQLISODateTime,
    },
    AuthService,
    UsersService,
  ],
})
export class AppModule {}
