/**
 * Interleaves elements of an array with additional elements generated by a provided function.
 *
 * @template T The type of the elements in the input array.
 * @template V The type of the elements generated by the function.
 * @param {T[]} a The input array to be interleaved.
 * @param {(prev: T | V, i: number) => V} o A function that generates a new element to interleave. It receives the previous element (either from the array or previously generated) and its index in the process.
 * @returns {(T | V)[]} A new array where elements from the input array are interleaved with the elements generated by the function.
 */
export const interleaveWithObject = <T, V>(a: T[], o: (prev: T | V, i: number) => V): (T | V)[] => {
  if (a.length < 2) {
    return a;
  }
  const r: (T | V)[] = [];
  let i = 0;
  for (; i < a.length - 1; ++i) {
    const prev = a[i];
    r.push(prev, o(prev, i));
  }
  r.push(a[i]);
  return r;
};
