-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "plannedStart" TIMESTAMP(3),
ADD COLUMN     "startAfter" TIMESTAMP(3),
ALTER COLUMN "priority" SET DEFAULT 5,
ALTER COLUMN "priority" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "urgency" SET DEFAULT 5,
ALTER COLUMN "urgency" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dueTo" DROP NOT NULL;
