import { DynamicModule, Injectable, Module, Provider } from '@nestjs/common';

import { getRandomBytes } from '../core';

/**
 * Represents service information, including its name, optional short name,
 * and a uniquely generated client name.
 *
 * This class is designed to be used for dependency injection in applications
 * that use dependency injection frameworks.
 *
 * It provides a factory method for generating a provider to inject an instance
 * of the ServiceInfo class with the specified parameters.
 *
 * The `clientName` is automatically generated by combining the name of the service
 * with a random hexadecimal identifier to ensure uniqueness.
 *
 * The constructor is protected, ensuring that this class cannot be directly instantiated
 * but is only accessible through the provided factory method.
 */
@Injectable()
export class ServiceInfo {
  public readonly name: string;
  public readonly shortName: string;
  public readonly clientName: string;

  protected constructor(name: string, shortName?: string) {
    this.name = name;
    this.shortName = shortName ?? name;

    const randomId = getRandomBytes.hex(4);
    this.clientName = `${this.name}-${randomId}`;
  }

  static provide(name: string, shortName?: string): Provider {
    return {
      provide: ServiceInfo,
      useFactory: () => new ServiceInfo(name, shortName),
    };
  }
}

@Module({})
export class ServiceInfoModule {
  /**
   * Configures and returns a globally scoped module with provided service information.
   *
   * @param {string} name - The name of the service being provided.
   * @param {string} [shortName] - An optional short name for the service.
   * @return {DynamicModule} A dynamic module configured as global with service information providers and exports.
   */
  static forRootGlobal(name: string, shortName?: string): DynamicModule {
    const serviceInfo = ServiceInfo.provide(name, shortName);
    return {
      module: ServiceInfoModule,
      global: true,
      providers: [serviceInfo],
      exports: [serviceInfo],
    };
  }
}
